service: email-subscription
frameworkVersion: '3'

custom:
  tableName: 'users-table-${sls:stage}'
  region: ${self:provider.region}
 
provider:
  name: aws
  stage: dev
  region: 'us-east-1'
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: SNS:publish
          Resource: !Ref QuotesMessages
        - Effect: Allow
          Action : "s3:*"
          Resource: "*"
        - Effect: Allow
          Action: 
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.tableName}
    REGION: ${self:provider.region}
    SNS_ARN_TOPIC: "arn:aws:sns:us-east-1:425448098132:quotes-messages-dev"

functions:
  api:
    handler: handler/getQuotes.getQuotes
    events:
      - http:
          path: quotes
          method: get
          cors: true
  subscribe:
    handler: handler/subscribeUser.subscribeUser
    events:
      - http:
          path: subscribe
          method: post
          cors: true
  staticMailer:
    handler: handler/staticMailer.staticMailer
    events:
      - http:
          path: static-mailer
          method: post
          cors: true
  sendEmail:
    handler: handler/sendEmail.sendEmail
    events:
      - http:
          path: sendEmail
          method: post
          cors: true
resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
    QuotesMessages:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: quotes-messages-${self:provider.stage}
    QuotesMessagesSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref QuotesMessages
        Protocol: email
        Endpoint: pkkashyap616@gmail.com
        DeliveryPolicy:
          healthyRetryPolicy:
            numRetries: 20
            minDelayTarget: 30
            maxDelayTarget: 600
            backoffFunction: exponential
